import Head from 'next/head'
import Image from 'next/image'
import React, { useRef } from 'react';
import styles from '../styles/Home.module.css'
import CarouselMain from './Carousel'
import CarouselHeroHome from './Carreacttest'
import AddIngredientNoLogin from './AddIngredient'
import RecepieCards from './RecipeCards'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      {/* <CarouselMain /> */}
      <CarouselHeroHome />
      
      
        <h1 className={styles.title}>
          Welcome to
        </h1>
        <br />
        <h1 className={styles.title} style={{color: 'blue'}}>
          USE IT UP!
        </h1>

        <p className={styles.description}>
          Discover World Class Receipes that use up the extra ingredients you have on hand!
        </p>

        <p>
          Try it out with a single ingredinet or create a free account to add multiple ingredients, save recipies and more!
        </p>

        <div className = "container-fluid">
         <div className = "row">
            <div className = "col-sm-9 col-md-6 col-lg-4">
            <RecepieCards />
            </div>
            <div className = "col-sm-9 col-md-6 col-lg-4">
            <RecepieCards />
            </div>
            <div className = "col-sm-9 col-md-6 col-lg-4">
            <RecepieCards />
            </div>
            <div className = "col-sm-9 col-md-6 col-lg-4">
            <RecepieCards />
            </div>
         </div>
      </div>

        <AddIngredientNoLogin />
        <div>
        <RecepieCards />
        <RecepieCards />

        </div>

        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
